version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: heatmap-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heatmap_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build: .
    container_name: heatmap-flask
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
